
require(["views/ast", "views/input", "views/status",
         "app/tokenizer", "app/parser", "app/languages"], 
        function(AST, Input, Status, Tk, Parser, L) {
    
    var parser = new Parser(L.test);    // for now, we'll hard-code this.  change it up later
    
    // for now, the only events will be generated by the 'parse'
    //   button.  nothing else will generate events
    
    $(document).ready(function() {
        var status = new Status($("#status")),
            ast    = new AST($("#ast"));
        
        function action(str) {
            var result, tree, rest;
            try {
                console.log('input: ' + str);
                result = parser.expr(Tk(str));
                console.log(JSON.stringify(result));
                tree = result[0], rest = result[1];
                if ( rest.length > 0 ) {
                    console.log('oops, some left');
                    status.display('success', 'there were some tokens left over: ' + JSON.stringify(rest));
                } else {
                    console.log('good to go');
                    status.display('success', 'everything worked fine');
                }
                ast.display(tree);
            } catch(e) {
                console.log('an error occurred: ' + e + JSON.stringify(e));
                status.display('error', JSON.stringify(e) + ' ' + e.message); // doesn't work on Error instances ???
                ast.display('');
            }
        }
        
        var input = new Input($("#input"), action);
    });
    
});
